title: Neural QA with DBpedia
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://mehrzadshm.github.io/GSoC-2023

aux_links:
  Project's GitHub Repo: https://github.com/dbpedia/neural-qa
