title: GSoC 2023 with DBpedia
description: GSoC 2023 project page
theme: just-the-docs

url: https://mehrzadshm.github.io/GSoC-2023

aux_links:
  Project's GitHub Repo: https://github.com/dbpedia/neural-qa
